package controller;

import classes.User;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JPanel;
import resources.en_translations.Translations;
import resources.style.Style;
import services.UserService;

/**
 * RegisterPanel Class.
 *
 * Class to define the GUI that allow make a new register in the APP and store in DB.
 *
 * @author Jorge Vázquez Casaus.
 * @version 1.0.
 * @see LoadPanels
 * @since 16/12/2022.
 */
public class RegisterPanel extends javax.swing.JPanel {

    private UserService userService;

    /**
     * Creates new form RegisterPanel. RegisterPanel class constructor.
     * 
     * @param workPanel WorkPanel, its the work area of the APP.
     */
    public RegisterPanel(JPanel workPanel) {
        this.userService = new UserService();
        this.workPanel = workPanel;
        initComponents();
        setComponents();
    }

    /**
     * Sets the componets with specific behaviour.
     */
    public void setComponents() {
        this.buyButton.setBorder(BorderFactory.createEmptyBorder());
        this.buyButton.setOpaque(false);
        this.buyButton.setContentAreaFilled(false);
        this.buyButton.setBorderPainted(false);
        this.registerButton.setBorder(BorderFactory.createEmptyBorder());
        this.registerButton.setOpaque(false);
        this.registerButton.setContentAreaFilled(false);
        this.registerButton.setBorderPainted(false);
        this.showPasswordButton.setBorder(BorderFactory.createEmptyBorder());
        this.showPasswordButton.setOpaque(false);
        this.showPasswordButton.setContentAreaFilled(false);
        this.showPasswordButton.setBorderPainted(false);
        this.backToLoginPanelButton.setBorder(BorderFactory.createEmptyBorder());
        this.backToLoginPanelButton.setOpaque(false);
        this.backToLoginPanelButton.setContentAreaFilled(false);
        this.backToLoginPanelButton.setBorderPainted(false);
        this.userNameTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        this.userNameTextField.setBackground(new java.awt.Color(0, 0, 0, 1));
        this.emailTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        this.emailTextField.setBackground(new java.awt.Color(0, 0, 0, 1));
        this.passwordField.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        this.passwordField.setBackground(new java.awt.Color(0, 0, 0, 1));
        this.errorLabel.setVisible(false);
        this.successLabel.setVisible(false);
        this.backToLoginPanelLabel.setVisible(false);
    }

    /**
     * Sets the componets with specific behaviour.
     */
    public void setErrorLabel() {
        this.errorLabel.setVisible(true);
        this.successLabel.setVisible(false);
        this.backToLoginPanelLabel.setVisible(false);
    }

    /**
     * Set the label that set an specific success message.
     */
    public void setSuccessLabel() {
        this.errorLabel.setVisible(false);
        this.successLabel.setVisible(true);
        this.backToLoginPanelLabel.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        workPanel = new javax.swing.JPanel();
        headerSeparator = new javax.swing.JSeparator();
        headerLabel = new javax.swing.JLabel();
        inputPanel = new javax.swing.JPanel();
        successLabel = new javax.swing.JLabel();
        backToLoginPanelLabel = new javax.swing.JLabel();
        errorLabel = new javax.swing.JLabel();
        registerButton = new javax.swing.JButton();
        userNameLabel = new javax.swing.JLabel();
        userNameTextField = new javax.swing.JTextField();
        userNameSeparator = new javax.swing.JSeparator();
        emaiLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        emailSeparator = new javax.swing.JSeparator();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        passwordSeparator = new javax.swing.JSeparator();
        showPasswordButton = new javax.swing.JButton();
        ageSpinner = new javax.swing.JSpinner();
        ageLabel = new javax.swing.JLabel();
        registerLayutLabel = new javax.swing.JLabel();
        registerPanel = new javax.swing.JPanel();
        areYouRegisteredLabel = new javax.swing.JLabel();
        backToLoginPanelButton = new javax.swing.JButton();
        actionBarPanel = new javax.swing.JPanel();
        userInfoPanel = new javax.swing.JPanel();
        notLogedYet = new javax.swing.JLabel();
        userNameInfoLabel = new javax.swing.JLabel();
        buyPanel = new javax.swing.JPanel();
        buyButton = new javax.swing.JButton();
        placeAnOrderLabel = new javax.swing.JLabel();

        setOpaque(false);

        workPanel.setOpaque(false);
        workPanel.setLayout(null);

        headerSeparator.setBackground(new java.awt.Color(0, 0, 0));
        headerSeparator.setForeground(new java.awt.Color(0, 0, 0));
        workPanel.add(headerSeparator);
        headerSeparator.setBounds(10, 130, 1230, 10);

        headerLabel.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        headerLabel.setForeground(new java.awt.Color(0, 0, 0));
        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setText("JOIN US AS NEW MEMBER!");
        workPanel.add(headerLabel);
        headerLabel.setBounds(0, 90, 1260, 40);

        inputPanel.setOpaque(false);
        inputPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        successLabel.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        successLabel.setForeground(new java.awt.Color(0, 204, 51));
        successLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        successLabel.setText("You have successfully registered!");
        inputPanel.add(successLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 320, 30));

        backToLoginPanelLabel.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        backToLoginPanelLabel.setForeground(new java.awt.Color(0, 204, 51));
        backToLoginPanelLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backToLoginPanelLabel.setText(" Please, go back to the login panel to access.");
        inputPanel.add(backToLoginPanelLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, 360, 30));

        errorLabel.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        errorLabel.setForeground(new java.awt.Color(204, 0, 0));
        errorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorLabel.setText("<<ERROR HERE>>");
        inputPanel.add(errorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, 260, 30));

        registerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/buttons/registerButton.png"))); // NOI18N
        registerButton.setOpaque(false);
        registerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registerButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registerButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                registerButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                registerButtonMouseReleased(evt);
            }
        });
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        inputPanel.add(registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 120, 200, 310));

        userNameLabel.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        userNameLabel.setForeground(new java.awt.Color(255, 102, 0));
        userNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        userNameLabel.setText("Username:");
        inputPanel.add(userNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 90, -1));

        userNameTextField.setForeground(new java.awt.Color(153, 153, 153));
        userNameTextField.setText("Enter here your username.");
        userNameTextField.setOpaque(false);
        userNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userNameTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userNameTextFieldFocusLost(evt);
            }
        });
        inputPanel.add(userNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 170, 30));

        userNameSeparator.setBackground(new java.awt.Color(204, 102, 0));
        inputPanel.add(userNameSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 170, 10));

        emaiLabel.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        emaiLabel.setForeground(new java.awt.Color(255, 102, 0));
        emaiLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        emaiLabel.setText("E-mail:");
        inputPanel.add(emaiLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 90, -1));

        emailTextField.setForeground(new java.awt.Color(153, 153, 153));
        emailTextField.setText("Enter here your email.");
        emailTextField.setOpaque(false);
        emailTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailTextFieldFocusLost(evt);
            }
        });
        inputPanel.add(emailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 170, 30));

        emailSeparator.setBackground(new java.awt.Color(204, 102, 0));
        inputPanel.add(emailSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, 170, 10));

        passwordLabel.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(255, 102, 0));
        passwordLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        passwordLabel.setText("Password:");
        inputPanel.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 90, -1));

        passwordField.setForeground(new java.awt.Color(153, 153, 153));
        passwordField.setText("Password.");
        passwordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFieldFocusLost(evt);
            }
        });
        inputPanel.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, 170, 30));

        passwordSeparator.setBackground(new java.awt.Color(204, 102, 0));
        inputPanel.add(passwordSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, 170, 10));

        showPasswordButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/buttons/show_password.png"))); // NOI18N
        showPasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordButtonActionPerformed(evt);
            }
        });
        inputPanel.add(showPasswordButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 250, 60, 50));

        ageSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 99, 1));
        ageSpinner.setFocusable(false);
        ageSpinner.setOpaque(false);
        inputPanel.add(ageSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, 170, 30));

        ageLabel.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        ageLabel.setForeground(new java.awt.Color(255, 102, 0));
        ageLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ageLabel.setText("Age:");
        inputPanel.add(ageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 90, -1));

        registerLayutLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/layout/register_layout.png"))); // NOI18N
        inputPanel.add(registerLayutLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, -20, 1210, 570));

        registerPanel.setForeground(new java.awt.Color(0, 0, 0));
        registerPanel.setOpaque(false);
        registerPanel.setLayout(null);

        areYouRegisteredLabel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        areYouRegisteredLabel.setForeground(new java.awt.Color(0, 0, 0));
        areYouRegisteredLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        areYouRegisteredLabel.setText("Are you registered?");
        areYouRegisteredLabel.setToolTipText("");
        registerPanel.add(areYouRegisteredLabel);
        areYouRegisteredLabel.setBounds(0, 10, 370, 23);

        backToLoginPanelButton.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        backToLoginPanelButton.setForeground(new java.awt.Color(0, 153, 255));
        backToLoginPanelButton.setText("Back to Login Panel");
        backToLoginPanelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backToLoginPanelButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backToLoginPanelButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backToLoginPanelButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                backToLoginPanelButtonMouseReleased(evt);
            }
        });
        backToLoginPanelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToLoginPanelButtonActionPerformed(evt);
            }
        });
        registerPanel.add(backToLoginPanelButton);
        backToLoginPanelButton.setBounds(0, 40, 370, 30);

        inputPanel.add(registerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 450, 370, 70));

        workPanel.add(inputPanel);
        inputPanel.setBounds(0, 150, 1260, 540);

        actionBarPanel.setBackground(new java.awt.Color(51, 51, 51));
        actionBarPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        actionBarPanel.setName("actionBarPanel"); // NOI18N
        actionBarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userInfoPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        userInfoPanel.setOpaque(false);
        userInfoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        notLogedYet.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        notLogedYet.setForeground(new java.awt.Color(255, 255, 255));
        notLogedYet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        notLogedYet.setText("Hi: Not logged yet.");
        notLogedYet.setName("userNameLabel"); // NOI18N
        userInfoPanel.add(notLogedYet, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 190, 20));

        userNameInfoLabel.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        userNameInfoLabel.setForeground(new java.awt.Color(255, 255, 255));
        userNameInfoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icons/user_icon_40x40.png"))); // NOI18N
        userNameInfoLabel.setName("userIconLabel"); // NOI18N
        userInfoPanel.add(userNameInfoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 40));

        actionBarPanel.add(userInfoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 1, 270, 80));

        buyPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        buyPanel.setOpaque(false);
        buyPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buyButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/buttons/shopping_car_disabled_70x40.png"))); // NOI18N
        buyButton.setName("buyButton"); // NOI18N
        buyPanel.add(buyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 70, 40));

        placeAnOrderLabel.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        placeAnOrderLabel.setForeground(new java.awt.Color(255, 255, 255));
        placeAnOrderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        placeAnOrderLabel.setText("Place an order");
        placeAnOrderLabel.setName("placeAnOrderLabel"); // NOI18N
        buyPanel.add(placeAnOrderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 130, 20));

        actionBarPanel.add(buyPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 1, -1, 80));

        workPanel.add(actionBarPanel);
        actionBarPanel.setBounds(0, 0, 1270, 81);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(workPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1270, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(workPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Check if the fields are valid. If all is correct, register a new user in
     * the APP and store it in the DB.
     *
     * @param evt Default event for Action Performed.
     */
    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        String userName = this.userNameTextField.getText();
        String email = this.emailTextField.getText();
        String password = this.passwordField.getText();
        int age = (int) this.ageSpinner.getValue();
        try {
            this.userService.isValidUserName(userName);
            this.userService.isValidEmail(email);
            this.userService.isValidPassword(password);
            User user = this.userService.createByNameEmailPasswordAndAge(userName, email, password, age);
            this.userService.save(user);
            setSuccessLabel();
            this.areYouRegisteredLabel.setForeground(Color.decode(Style.GREEN_CODE_COLOR));
        } catch (Exception exception) {
            setErrorLabel();
            this.errorLabel.setText(exception.getMessage());
            return;
        }
    }//GEN-LAST:event_registerButtonActionPerformed

    /**
     * Clean the text of the email TextField.
     *
     * @param evt Default event for Focus Gained.
     */
    private void emailTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTextFieldFocusGained
        this.emailTextField.setText(Translations.EMPTY_STRING);
    }//GEN-LAST:event_emailTextFieldFocusGained

    /**
     * Recover the default text if email field is empty.
     *
     * @param evt Default event for Focus Lost.
     */
    private void emailTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTextFieldFocusLost
        if (this.emailTextField.getText().equals(Translations.EMPTY_STRING)) {
            this.emailTextField.setText(Translations.DEFAULT_EMAIL_TEXT);
        }
    }//GEN-LAST:event_emailTextFieldFocusLost

    /**
     * Clean the text of the password TextField.
     *
     * @param evt Default event for Focus Gained.
     */
    private void passwordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusGained
        this.passwordField.setText(Translations.EMPTY_STRING);
    }//GEN-LAST:event_passwordFieldFocusGained

    /**
     * Recover the default text if password field is empty.
     *
     * @param evt Default event for Focus Lost.
     */
    private void passwordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusLost
        if (this.passwordField.getText().equals(Translations.EMPTY_STRING)) {
            this.passwordField.setText(Translations.DEFAULT_PASSWORD_TEXT);
        }
    }//GEN-LAST:event_passwordFieldFocusLost

    /**
     * Make a hover in the register button.
     *
     * @param evt Default event for Mouse Entered.
     */
    private void registerButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerButtonMouseEntered
        this.registerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource(resources.style.Style.REGISTER_HOVER_BUTTON)));
    }//GEN-LAST:event_registerButtonMouseEntered

    /**
     * Recover the original icon of the register button.
     *
     * @param evt Default event for Mouse Exited.
     */
    private void registerButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerButtonMouseExited
        this.registerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource(resources.style.Style.REGISTER_BUTTON)));
    }//GEN-LAST:event_registerButtonMouseExited

    /**
     * Set the icon of the register button for clicked one.
     *
     * @param evt Default event for Mouse Pressed.
     */
    private void registerButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerButtonMousePressed
        this.registerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource(resources.style.Style.REGISTER_CLICKED_BUTTON)));
    }//GEN-LAST:event_registerButtonMousePressed

    /**
     * Recover the original icon of the register button when mouse released.
     *
     * @param evt Default event for Mouse Released.
     */
    private void registerButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerButtonMouseReleased
        this.registerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource(resources.style.Style.REGISTER_BUTTON)));
    }//GEN-LAST:event_registerButtonMouseReleased

    /**
     * Set purple the text color when mouse entered in the button.
     *
     * @param evt Defaut event for Mouse Entered.
     */
    private void backToLoginPanelButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backToLoginPanelButtonMouseEntered
        this.backToLoginPanelButton.setForeground(Color.decode(Style.PURPLE_CODE_COLOR));
    }//GEN-LAST:event_backToLoginPanelButtonMouseEntered

    /**
     * Recover the original blue color when mouse exited of the button.
     *
     * @param evt Defaut event for Mouse Exited.
     */
    private void backToLoginPanelButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backToLoginPanelButtonMouseExited
        this.backToLoginPanelButton.setForeground(Color.decode(Style.BLUE_CODE_COLOR));
    }//GEN-LAST:event_backToLoginPanelButtonMouseExited

    /**
     * Set red the text color when mouse click the button.
     *
     * @param evt Defaut event for Mouse Pressed.
     */
    private void backToLoginPanelButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backToLoginPanelButtonMousePressed
        this.backToLoginPanelButton.setForeground(Color.RED);
    }//GEN-LAST:event_backToLoginPanelButtonMousePressed

    /**
     * Recover the original blue color when mouse exited of the button.
     *
     * @param evt Defaut event for Mouse Released.
     */
    private void backToLoginPanelButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backToLoginPanelButtonMouseReleased
        this.backToLoginPanelButton.setForeground(Color.decode(Style.BLUE_CODE_COLOR));
    }//GEN-LAST:event_backToLoginPanelButtonMouseReleased

    /**
     * Loads the Loginpanel.
     *
     * @param evt Default event for Action Performed.
     */
    private void backToLoginPanelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToLoginPanelButtonActionPerformed
        LoadPanels loadPanels = new LoadPanels(this.workPanel);
        loadPanels.loadLoginPanel();
    }//GEN-LAST:event_backToLoginPanelButtonActionPerformed

    /**
     * Clean the text of the email TextField.
     *
     * @param evt Default event for Focus Gained.
     */
    private void userNameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameTextFieldFocusGained
        this.emailTextField.setText(Translations.EMPTY_STRING);
    }//GEN-LAST:event_userNameTextFieldFocusGained

    /**
     * Recover the default text if username field is empty.
     *
     * @param evt Default event for Focus Lost.
     */
    private void userNameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameTextFieldFocusLost
        if (this.emailTextField.getText().equals(Translations.EMPTY_STRING)) {
            this.emailTextField.setText(Translations.DEFAULT_EMAIL_TEXT);
        }
    }//GEN-LAST:event_userNameTextFieldFocusLost

    /**
     * Changes Hide/show password icon if password is hidded or visible.
     *
     * @param evt Defaut event for Action Performed.
     */
    private void showPasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordButtonActionPerformed
        if (passwordField.getEchoChar() == (Style.ASTERISC)) {
            this.passwordField.setEchoChar((char) 0);
            this.showPasswordButton.setIcon(new javax.swing.ImageIcon(getClass().getResource(Style.HIDE_PASSWORD_BUTTON)));
            return;
        }
        this.passwordField.setEchoChar(Style.ASTERISC);
        this.showPasswordButton.setIcon(new javax.swing.ImageIcon(getClass().getResource(Style.SHOW_PASSWORD_BUTTON)));
    }//GEN-LAST:event_showPasswordButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionBarPanel;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JSpinner ageSpinner;
    private javax.swing.JLabel areYouRegisteredLabel;
    private javax.swing.JButton backToLoginPanelButton;
    private javax.swing.JLabel backToLoginPanelLabel;
    private javax.swing.JButton buyButton;
    private javax.swing.JPanel buyPanel;
    private javax.swing.JLabel emaiLabel;
    private javax.swing.JSeparator emailSeparator;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JSeparator headerSeparator;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JLabel notLogedYet;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JSeparator passwordSeparator;
    private javax.swing.JLabel placeAnOrderLabel;
    private javax.swing.JButton registerButton;
    private javax.swing.JLabel registerLayutLabel;
    private javax.swing.JPanel registerPanel;
    private javax.swing.JButton showPasswordButton;
    private javax.swing.JLabel successLabel;
    private javax.swing.JPanel userInfoPanel;
    private javax.swing.JLabel userNameInfoLabel;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JSeparator userNameSeparator;
    private javax.swing.JTextField userNameTextField;
    private javax.swing.JPanel workPanel;
    // End of variables declaration//GEN-END:variables
}
