package classes;
// Generated 11-dic-2022 21:47:38 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrderProduct generated by hbm2java
 */
@Entity
@Table(name="orderProduct"
    ,catalog="virtual_market"
)
public class OrderProduct  implements java.io.Serializable {


     private Integer id;
     private Order order;
     private Product product;
     private Date entryDate;
     private Date modificationDate;

    public OrderProduct() {
    }

	
    public OrderProduct(Order order, Product product, Date entryDate) {
        this.order = order;
        this.product = product;
        this.entryDate = entryDate;
    }
    public OrderProduct(Order order, Product product, Date entryDate, Date modificationDate) {
       this.order = order;
       this.product = product;
       this.entryDate = entryDate;
       this.modificationDate = modificationDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="orderId", nullable=false)
    public Order getOrder() {
        return this.order;
    }
    
    public void setOrder(Order order) {
        this.order = order;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="productId", nullable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="entryDate", nullable=false, length=19)
    public Date getEntryDate() {
        return this.entryDate;
    }
    
    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modificationDate", length=19)
    public Date getModificationDate() {
        return this.modificationDate;
    }
    
    public void setModificationDate(Date modificationDate) {
        this.modificationDate = modificationDate;
    }




}


